### PR TITLE
Add support for the medicare surplus tax rate

### PR DESCRIPTION
**Pull request by thephw**
### Changes
- Adds support for the medicare surplus tax

### Reference
https://www.irs.gov/newsroom/what-is-the-additional-medicare-tax

### Acknowledgements
Hat tip to @alindeman and @mastahyeti for the info.

### CODE REVIEW

**Comment by alindeman** [comment]
My understanding is that the additional medicare tax is only on income above the threshold amount.

For instance, a single person making $210,000 would be taxed as: ($210,000 * 1.45%) + ($10,000 * 0.9%). Going above the threshold amount doesn't mean that _all_ income is taxed at the higher rate.

If it's more convenient, it should be possible to model this as if it were a marginal tax bracket system, just like regular income tax. In that case it'd be 1.45% up to $200,000 (single) and 2.35% from $200,000 to infinity.

**Comment by thephw** [comment]
I think you are right. The original article was a little vague, but this is marginally clearer from another IRS publication. The part in bold kind of tripped me up with the wording.

https://www.irs.gov/publications/p15#en_US_2020_publink1000286680

Additional Medicare Tax withholding.

In addition to withholding Medicare tax at 1.45%, you must withhold a 0.9% Additional Medicare Tax from wages you pay to an employee in excess of $200,000 in a calendar year. You’re required to begin withholding Additional Medicare Tax in the pay period in which you pay wages in excess of $200,000 to an employee and continue to withhold it each pay period until the end of the calendar year. Additional Medicare Tax is only imposed on the employee. There is no employer share of Additional Medicare Tax. _**All wages that are subject to Medicare tax are subject to Additional Medicare Tax withholding if paid in excess of the $200,000 withholding threshold.**_

**Comment by thephw** [comment]
Actually gives me an idea to unify the data model a bit. Social security to be modeled as:
```
    SOCIAL_SECURITY_TAX_RATES = {
      137_700 => 0.062,
      Float::INFINITY => 0.0,
    }
```

**Comment by thephw** [comment]
lol confused the hell out of myself with choosing arbitrarily bad test values

Old code:
```
[2] pry(main)> TaxablePerson.single("georgia", 300_000).take_home
=> 194376.1
```

New code:
```
[2] pry(main)> TaxablePerson.single("georgia", 300_000).take_home
=> 193476.1
```

**Comment by thephw** [comment]
194376.1 != 193476.1 but they look basically identical because that is how reading works.

**Pull request merged**
